export const CREATE_CATEGORY_REQUEST = 'CREATE_CATEGORY_REQUEST'
export const CREATE_CATEGORY_SUCCESS = 'CREATE_CATEGORY_SUCCESS'
export const CREATE_CATEGORY_RESET = 'CREATE_CATEGORY_RESET'
export const CREATE_CATEGORY_FAIL = 'CREATE_CATEGORY_FAIL'

export const DELETE_CATEGORY_REQUEST = 'DELETE_CATEGORY_REQUEST'
export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS'
export const DELETE_CATEGORY_RESET = 'DELETE_CATEGORY_RESET'
export const DELETE_CATEGORY_FAIL = 'DELETE_CATEGORY_FAIL'


export const UPDATE_CATEGORY_REQUEST = 'UPDATE_CATEGORY_REQUEST'
export const UPDATE_CATEGORY_SUCCESS = 'UPDATE_CATEGORY_SUCCESS'
export const UPDATE_CATEGORY_RESET = 'UPDATE_CATEGORY_RESET'
export const UPDATE_CATEGORY_FAIL = 'UPDATE_CATEGORY_FAIL'

export const ALL_CATEGORIES_REQUEST = 'ALL_CATEGORYS_REQUEST'
export const ALL_CATEGORIES_SUCCESS = 'ALL_CATEGORYS_SUCCESS'
export const ALL_CATEGORIES_FAIL = 'ALL_CATEGORYS_FAIL'

export const ONE_CATEGORIES_REQUEST = 'ONE_CATEGORYS_REQUEST'
export const ONE_CATEGORIES_SUCCESS = 'ONE_CATEGORYS_SUCCESS'
export const ONE_CATEGORIES_FAIL = 'ONE_CATEGORYS_FAIL'

export const DISPLAY_CATEGORYSUBS_REQUEST = 'DISPLAY_CATEGORYSUBS_REQUEST'
export const DISPLAY_CATEGORYSUBS_SUCCESS = 'DISPLAY_CATEGORYSUBS_SUCCESS'
export const DISPLAY_CATEGORYSUBS_RESET = 'DISPLAY_CATEGORYSUBS_RESET'
export const DISPLAY_CATEGORYSUBS_FAIL = 'DISPLAY_CATEGORYSUBS_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'