export const CREATE_SUB_REQUEST = 'CREATE_SUB_REQUEST'
export const CREATE_SUB_SUCCESS = 'CREATE_SUB_SUCCESS'
export const CREATE_SUB_RESET = 'CREATE_SUB_RESET'
export const CREATE_SUB_FAIL = 'CREATE_SUB_FAIL'

export const DELETE_SUB_REQUEST = 'DELETE_SUB_REQUEST'
export const DELETE_SUB_SUCCESS = 'DELETE_SUB_SUCCESS'
export const DELETE_SUB_RESET = 'DELETE_SUB_RESET'
export const DELETE_SUB_FAIL = 'DELETE_SUB_FAIL'


export const UPDATE_SUB_REQUEST = 'UPDATE_SUB_REQUEST'
export const UPDATE_SUB_SUCCESS = 'UPDATE_SUB_SUCCESS'
export const UPDATE_SUB_RESET = 'UPDATE_SUB_RESET'
export const UPDATE_SUB_FAIL = 'UPDATE_SUB_FAIL'

export const ALL_SUBS_REQUEST = 'ALL_SUBS_REQUEST'
export const ALL_SUBS_SUCCESS = 'ALL_SUBS_SUCCESS'
export const ALL_SUBS_FAIL = 'ALL_SUBS_FAIL'

export const ONE_SUBS_REQUEST = 'ONE_SUBS_REQUEST'
export const ONE_SUBS_SUCCESS = 'ONE_SUBS_SUCCESS'
export const ONE_SUBS_FAIL = 'ONE_SUBS_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'